### ISSUE TITLE
compile wasm for external contracts in setup script

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis#35]
In `./local_*_setup.sh` we are using wasm files stored in `e2e/wasm` repo. 

This is not ideal and hard to maintain for versioning. We should build the wasm from versioned code.

**Comment by j0nl1** [comment]
We could add the contracts like a git submodule and always have the latest version in order to build and deploy them.
Another possible solution could be to fetch the contracts with a curl.

This two approach could have an issue like there is a possibility where the smart contract have a breaking change?

**Comment by whalelephant** [comment]
https://github.com/DA0-DA0/dao-contracts/blob/main/scripts/deploy_local.sh#L47

With curl it looks like we can at least specify the release for cw-plus contracts - which we use the `cw3_fixed_multisig.wasm` and the `cw20-base` ones.

However, before `dao-contracts` v1 get released, we probably cannot use the build, because there is conflict in building to wasm, even with the [workspace-optimizer](https://github.com/CosmWasm/rust-optimizer). I followed the advice on discord to delete dir and update workspace in order to get the current wasm files. 

I think for now, we can only update with cw-plus contracts.

**Comment by sascha1337** [comment]
i had the same issue, building some tooling around da0da0 repo in the past. the rust|workspace-optimizer images are _too static/hardcoded_ for more complex repo structures, indeed!

fiddled around a lot, **until** i found some very helpful cargo helper tool named `Dors` - `cargo install dors`, it can be used as a replacement for cargo run-script, and seems to a super simple but flexible-workspace-aware `npm/yarn run` equivalent for rust/cargo. 

How did Dors fix my issues on similar problem as you got: 
- you can have a root level Dorsfile.toml
- you can hook commands before/after each script ( kinda like husky )
- you can combine that with npm/yarn/bash scripts without problems
- The BEST function it has, is the option to place another Dorsfile.toml into any cargo workspace child/contract folder, and overwrite/extend the root level Dorsfile. 

I can recommend to give it a try, this was a timesaving game-changer for me, without adding complexity. Also results in less bash scripts and hardcoded paths. 

Been able to replace cargo run-script, any .cargo/config files and cargo optimize docker commands with Dorsfiles. :fire:

**Comment by whalelephant** [comment]
I think we can do this now with the new contracts. 

https://github.com/DA0-DA0/dao-contracts/releases/tag/v1.0.0
