### ISSUE TITLE
Frozen accounts should allow guardians to do key rotation

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis#40]
Writing up discussions with @giovanni-orciuolo 

In the case where a wallet has been frozen (by guardians at the request of the user) and the user wants the guardian to rotate the user key, the guardian should be able to rotate the key without unfreezing the wallet first. This is important as unfreezing it may allow a malicious actor with the old user key to  update the list of guardians.

**Comment by giovanni-orciuolo** [comment]
Unfreezing it may also allow the attacker to send all funds of SCW to his own addresses

**Comment by egidiocasati** [comment]
Agree. In real world, freezing would be mainly used by the holder to sort out critical situations (potentially lost device). If the only way to solve those situations is setting up a new local wallet, key rotation must happen when the account is still frozen. so i totally agree
