### ISSUE TITLE
Use the cosmwasm repo dependency

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis#73]
@pyramation 's repo has now been moved to under the cosmwasm org and we should update our dependencies.

https://github.com/CosmWasm/cosmwasm-typescript-gen

**Comment by j0nl1** [comment]
I think we can close this issue since the library has not changed in the npm registry.

**Comment by sascha1337** [comment]
actually, it is available now, on npm, as @cosmwasm/ts-codegen

**Comment by sascha1337** [comment]
https://www.npmjs.com/package/@cosmwasm/ts-codegen
