### ISSUE TITLE
Update dependencies to dao-contracts v1

### ISSUE THREAD

**Issue by whalelephant** [nymlab/vectis#76]
We should update contract dependencies to use the v1 release 

https://github.com/DA0-DA0/dao-contracts/releases/tag/v1.0.0

**Comment by whalelephant** [comment]
Specifically in the CLI - https://github.com/nymlab/vectis/blob/8e1ed1d21e0432bc0f75e1d218aee0df111c6c52/cli/core/utils/dao-deploy.ts#L77

**Comment by sascha1337** [comment]
ouh, so all the code is not yet using v1 of daodao ? if thats the case, i'd increase the importance weight of this issue here a bit, pretty important.

**Comment by whalelephant** [comment]
Updated to v2
